CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
   "MigrationId" character varying(150) NOT NULL,
   "ProductVersion" character varying(32) NOT NULL,
   CONSTRAINT "PK_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE dividends (
                           dividend_id bigint GENERATED BY DEFAULT AS IDENTITY,
                           contract_id bigint NOT NULL,
                           ex_dividend_date timestamp with time zone NOT NULL,
                           amount double precision NOT NULL,
                           CONSTRAINT "PK_dividends" PRIMARY KEY (dividend_id)
);

CREATE TABLE dollar_value_bau (
                                  stream_id bigint NOT NULL,
                                  open_dt timestamp with time zone NOT NULL,
                                  close_dt timestamp with time zone NOT NULL,
                                  open double precision NOT NULL,
                                  high double precision NOT NULL,
                                  low double precision NOT NULL,
                                  close double precision NOT NULL,
                                  face_volume double precision NOT NULL,
                                  dollar_value double precision NOT NULL
);

CREATE TABLE face_volume_bau (
                                 stream_id bigint NOT NULL,
                                 open_dt timestamp with time zone NOT NULL,
                                 close_dt timestamp with time zone NOT NULL,
                                 open double precision NOT NULL,
                                 high double precision NOT NULL,
                                 low double precision NOT NULL,
                                 close double precision NOT NULL,
                                 face_volume double precision NOT NULL,
                                 dollar_value double precision NOT NULL
);

CREATE TABLE rolling_contracts (
                                   id integer GENERATED BY DEFAULT AS IDENTITY,
                                   parent_contract_id bigint NOT NULL,
                                   contract_id bigint NOT NULL,
                                   start_dt timestamp with time zone NOT NULL,
                                   end_dt timestamp with time zone NOT NULL,
                                   CONSTRAINT "PK_rolling_contracts" PRIMARY KEY (id)
);

CREATE TABLE splits (
                        split_id bigint GENERATED BY DEFAULT AS IDENTITY,
                        contract_id bigint NOT NULL,
                        dt timestamp with time zone NOT NULL,
                        factor double precision NOT NULL,
                        CONSTRAINT "PK_splits" PRIMARY KEY (split_id)
);

CREATE TABLE time_bau (
                          stream_id bigint NOT NULL,
                          open_dt timestamp with time zone NOT NULL,
                          close_dt timestamp with time zone NOT NULL,
                          open double precision NOT NULL,
                          high double precision NOT NULL,
                          low double precision NOT NULL,
                          close double precision NOT NULL,
                          face_volume double precision NOT NULL,
                          dollar_value double precision NOT NULL
);

CREATE INDEX "IX_dividends_contract_id" ON dividends (contract_id);

CREATE INDEX "IX_dividends_dividend_id" ON dividends (dividend_id);

CREATE INDEX "IX_dividends_ex_dividend_date" ON dividends (ex_dividend_date);

CREATE INDEX "IX_rolling_contracts_contract_id" ON rolling_contracts (contract_id);

CREATE INDEX "IX_rolling_contracts_end_dt" ON rolling_contracts (end_dt);

CREATE INDEX "IX_rolling_contracts_parent_contract_id" ON rolling_contracts (parent_contract_id);

CREATE INDEX "IX_rolling_contracts_start_dt" ON rolling_contracts (start_dt);

CREATE INDEX "IX_splits_contract_id" ON splits (contract_id);

CREATE INDEX "IX_splits_dt" ON splits (dt);

SELECT create_hypertable('"time_bau"', 'open_dt');
CREATE INDEX ix_time_bau_symbol_time_time ON "time_bau" ("stream_id", "open_dt" ASC, "close_dt" ASC);
SELECT create_hypertable( '"face_volume_bau"', 'open_dt');
CREATE INDEX ix_face_volume_bau_symbol_time_time ON "face_volume_bau" ("stream_id", "open_dt" ASC, "close_dt" ASC);
SELECT create_hypertable( '"dollar_value_bau"', 'open_dt');
CREATE INDEX ix_dollar_value_bau_symbol_time_time ON "dollar_value_bau" ("stream_id", "open_dt" ASC, "close_dt" ASC);

CREATE OR REPLACE FUNCTION numeric_mul(
	state NUMERIC,
	next NUMERIC
)
RETURNS NUMERIC
LANGUAGE SQL
AS
$func$
SELECT state * next;
$func$;

CREATE OR REPLACE FUNCTION double_mul(
	state double precision,
	next double precision
)
RETURNS double precision
LANGUAGE SQL
AS
$func$
SELECT state * next;
$func$;

CREATE OR REPLACE AGGREGATE MUL(numeric) (
	sfunc = numeric_mul,
	stype = numeric,
	initcond = 1
);

CREATE OR REPLACE AGGREGATE MUL(double precision) (
	sfunc = double_mul,
	stype = double precision,
	initcond = 1
);


CREATE FOREIGN TABLE IF NOT EXISTS public.contracts (
	contract_id bigint NOT NULL,
    ticker text COLLATE pg_catalog."default" NOT NULL,
    type TEXT NOT NULL,
    parent_contract_id bigint,
    first_trading_dt timestamp with time zone,
    expiration_dt timestamp with time zone,
    rollover_dt timestamp with time zone,
    primary_datafeed_id bigint
)
SERVER main 
OPTIONS (table_name 'contracts');
CREATE FOREIGN TABLE IF NOT EXISTS public.streams (
	contract_id BIGINT NOT NULL,
	stream_id BIGINT NOT NULL,
	datafeed_id BIGINT NOT NULL
)
SERVER main 
OPTIONS (table_name 'streams');

CREATE OR REPLACE FUNCTION public.get_stream_time_bau_start_end(
	stream bigint,
	start_dt timestamp with time zone,
	end_dt timestamp with time zone
)
RETURNS TABLE(
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision
)
LANGUAGE 'sql'
VOLATILE PARALLEL UNSAFE
ROWS 500000
AS $BODY$

SELECT
    stream_id,
    open_dt,
    close_dt,
    open,
    high,
    low,
    close,
    face_volume,
    dollar_value
FROM
    public.time_bau b
WHERE
    b.stream_id = stream
  AND b.open_dt > start_dt
  AND b.close_dt <= end_dt

$BODY$;

CREATE OR REPLACE FUNCTION public.get_stream_time_bau_end_num(
	stream bigint,
	end_dt timestamp with time zone,
 	number_of_bars int
)
RETURNS TABLE(
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision
)
LANGUAGE 'sql'
VOLATILE PARALLEL UNSAFE
ROWS 500000
AS $BODY$

SELECT
    *
FROM
    (
        SELECT
            stream_id,
            open_dt,
            close_dt,
            open,
            high,
            low,
            close,
            face_volume,
            dollar_value
        FROM
            public.time_bau b
        WHERE
            b.stream_id = stream
          AND b.close_dt <= end_dt
        ORDER BY
            b.close_dt DESC
            LIMIT number_of_bars
    ) sel
ORDER BY
    close_dt ASC

    $BODY$;

CREATE OR REPLACE FUNCTION public.get_contract_time_bau_start_end(
	contract bigint,
	start_dt timestamp with time zone,
	end_dt timestamp with time zone
)
RETURNS TABLE (
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision, 
	total_dividends double precision, 
	factor double precision
)
LANGUAGE 'sql'
VOLATILE PARALLEL UNSAFE
AS $BODY$
WITH bars AS (
	SELECT
		bau.stream_id,
		bau.open_dt,
		bau.close_dt,
		bau.open,
		bau.high,
		bau.low,
		bau.close,
		bau.face_volume as volume,
		bau.dollar_value
	FROM 
		public.time_bau bau
	WHERE
		bau.stream_id = (
			SELECT 
				s.stream_id 
			FROM 
				public.contracts c
				INNER JOIN public.streams s on s.contract_id = c.contract_id and s.datafeed_id = c.primary_datafeed_id
			WHERE 
				c.contract_id = contract
			LIMIT 1
		)
		AND bau.open_dt >= start_dt
		AND bau.open_dt < end_dt
	ORDER BY 
		bau.close_dt
), series as (
	SELECT
		*
	FROM
		generate_series(start_dt, end_dt, INTERVAL '1 minute') dt
), dividends AS (
	SELECT
		d.ex_dividend_date as dt,
		d.amount / COALESCE(MUL(s.factor), 1) as adjusted_amount
	FROM
		public.dividends d
		LEFT JOIN public.splits s ON s.dt > d.ex_dividend_date AND s.dt < end_dt
	WHERE
		d.contract_id = contract
		AND d.ex_dividend_date > start_dt
		AND d.ex_dividend_date < end_dt
	GROUP BY
		d.ex_dividend_date,
		d.amount
), normalized_dividends AS (
	SELECT
		s.dt,
		SUM(d.adjusted_amount) AS total_dividends
	FROM
		series s
		LEFT JOIN dividends d ON 
			d.dt > s.dt
	GROUP BY
		s.dt
), normalized_splits AS (
	SELECT
		s.dt,
		MUL(sp.factor) AS factor
	FROM
		series s
		LEFT JOIN public.splits sp ON 
			sp.contract_id = contract
			AND sp.dt > s.dt
			AND sp.dt < end_dt
	GROUP BY
		s.dt
), raw AS (
	SELECT
		bars.stream_id,
		bars.open_dt,
		bars.close_dt,
		bars.open,
		bars.high,
		bars.low,
		bars.close,
		bars.volume,
		bars.dollar_value,
		COALESCE(d.total_dividends, 0) AS total_dividends,
		COALESCE(s.factor, 1) AS factor
	FROM
		bars
		LEFT JOIN normalized_dividends d on d.dt = bars.open_dt
		LEFT JOIN normalized_splits s on s.dt = bars.open_dt
)
SELECT
    stream_id,
    open_dt,
    close_dt,
    open / factor - total_dividends AS open,
    high / factor - total_dividends AS high,
    low / factor - total_dividends AS low,
    close / factor - total_dividends AS close,
    volume * factor AS volume,
    dollar_value,
    total_dividends,
    factor
FROM
    raw

    $BODY$;

CREATE OR REPLACE FUNCTION public.get_contract_time_bau_end_num (
	contract bigint,
	end_dt timestamp with time zone,
	num_bars int,
	adj_finish_dt timestamp with time zone
)
RETURNS TABLE (
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision, 
	total_dividends double precision, 
	factor double precision
)
LANGUAGE 'sql'
VOLATILE PARALLEL UNSAFE
AS $BODY$
WITH bars AS (
	SELECT
		*
	FROM
	(
		SELECT
			bau.stream_id,
			bau.open_dt,
			bau.close_dt,
			bau.open,
			bau.high,
			bau.low,
			bau.close,
			bau.face_volume as volume,
			bau.dollar_value
		FROM 
			public.time_bau bau
		WHERE
			bau.stream_id = (
				SELECT 
					s.stream_id 
				FROM 
					public.contracts c
					INNER JOIN public.streams s on s.contract_id = c.contract_id and s.datafeed_id = c.primary_datafeed_id
				WHERE 
					c.contract_id = contract
				LIMIT 1
			)
			AND bau.close_dt <= end_dt		
		ORDER BY 
			bau.close_dt DESC
			LIMIT num_bars
	) sel
	ORDER BY
		close_dt ASC
), min_dt as (
	SELECT MIN(open_dt) as min_dt FROM bars LIMIT 1
), series as (
	SELECT
		*
	FROM
		generate_series((select min_dt from min_dt), adj_finish_dt, INTERVAL '1 minute') dt
), dividends AS (
	SELECT
		d.ex_dividend_date as dt,
		d.amount / COALESCE(MUL(s.factor), 1) as adjusted_amount
	FROM
		public.dividends d
		LEFT JOIN public.splits s ON s.dt > d.ex_dividend_date AND s.dt < adj_finish_dt
	WHERE
		d.contract_id = contract
		AND d.ex_dividend_date > (select min_dt from min_dt)
		AND d.ex_dividend_date < adj_finish_dt
	GROUP BY
		d.ex_dividend_date,
		d.amount
), normalized_dividends AS (
	SELECT
		s.dt,
		SUM(d.adjusted_amount) AS total_dividends
	FROM
		series s
		LEFT JOIN dividends d ON 
			d.dt > s.dt
	GROUP BY
		s.dt
), normalized_splits AS (
	SELECT
		s.dt,
		MUL(sp.factor) AS factor
	FROM
		series s
		LEFT JOIN public.splits sp ON 
			sp.contract_id = contract
			AND sp.dt > s.dt
			AND sp.dt < adj_finish_dt
	GROUP BY
		s.dt
), raw AS (
	SELECT
		bars.stream_id,
		bars.open_dt,
		bars.close_dt,
		bars.open,
		bars.high,
		bars.low,
		bars.close,
		bars.volume,
		bars.dollar_value,
		COALESCE(d.total_dividends, 0) AS total_dividends,
		COALESCE(s.factor, 1) AS factor
	FROM
		bars
		LEFT JOIN normalized_dividends d on d.dt = bars.open_dt
		LEFT JOIN normalized_splits s on s.dt = bars.open_dt
)
SELECT
    stream_id,
    open_dt,
    close_dt,
    open / factor - total_dividends AS open,
    high / factor - total_dividends AS high,
    low / factor - total_dividends AS low,
    close / factor - total_dividends AS close,
    volume * factor AS volume,
    dollar_value,
    total_dividends,
    factor
FROM
    raw
ORDER BY
    open_dt ASC

    $BODY$;

CREATE OR REPLACE FUNCTION public.get_futures_time_bau_start_end(
	contract bigint,
	start_dt timestamp with time zone,
	end_dt timestamp with time zone,
	use_futures_no integer DEFAULT 0
)
RETURNS TABLE(
	stream_id BIGINT,
	open_dt timestamp with time zone,
	close_dt timestamp with time zone,
	open double precision,
	high double precision,
	low double precision,
	close double precision,
	face_volume double precision,
	dollar_value double precision,
	contract_id bigint,
	period bigint
)
LANGUAGE 'sql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
	
WITH prices AS
(
	SELECT
		*
	FROM
		(
			SELECT
				GREATEST(MIN(sel.dt) - INTERVAL '1 minute', start_dt) AS start,
				MAX(sel.dt) AS end,
				sel.contract_id,
				sel.period - use_futures_no AS period
			FROM
				(
					SELECT 
						series.dt,
						contracts.contract_id,
						contracts.period,
						ROW_NUMBER() OVER (PARTITION BY series.dt ORDER BY contracts.rollover_dt ASC) as contract_no
					FROM 
						(
							SELECT generate_series as dt FROM generate_series(start_dt, end_dt, INTERVAL '1 minute')
						) series
						LEFT JOIN
						(
							SELECT
								c.contract_id,
								c.first_trading_dt,
								c.rollover_dt,
								ROW_NUMBER() OVER () as period
							FROM
								public.contracts c
							WHERE
								c.parent_contract_id = contract
								AND c.rollover_dt >= start_dt
							ORDER BY
								rollover_dt
						) contracts ON contracts.rollover_dt >= series.dt AND contracts.first_trading_dt <= series.dt
				) sel
			WHERE
				sel.contract_no = use_futures_no + 1
			GROUP BY
				sel.contract_id, sel.period
		) periods
		INNER JOIN LATERAL 
			public.get_contract_time_bau_start_end(periods.contract_id, GREATEST(periods.start - INTERVAL '1 minute', start_dt), periods.end) ON true
), rollovers AS
(
	SELECT
		sel.period,
		sel.delta,
		SUM(sel.delta) OVER (ORDER BY sel.period DESC) as total_delta
	FROM
	(
		SELECT
			p.period,
			n.close - p.close as delta
		FROM
			prices p
			LEFT JOIN prices n on n.start = p.end
		WHERE
			p.close_dt = p.end
			AND n.open_dt < n.start
	) sel
), raw AS
(
	SELECT
		main.stream_id,
		main.open_dt as dt,
		main.close_dt,
		main.open + COALESCE(r.total_delta, 0) AS open,
		main.high + COALESCE(r.total_delta, 0) AS high,
		main.low + COALESCE(r.total_delta, 0) AS low,
		main.close + COALESCE(r.total_delta, 0) AS close,
		main.face_volume,
		main.dollar_value,
		main.contract_id,
		main.period
	FROM
		prices main
		LEFT JOIN rollovers r ON r.period = main.period
	WHERE
		main.open_dt >= main.start
)
SELECT
    stream_id,
    dt as open_dt,
    close_dt,
    open,
    high,
    low,
    close,
    face_volume,
    dollar_value,
    contract_id,
    period
FROM
    raw
ORDER BY
    open_dt;
$BODY$;


CREATE OR REPLACE FUNCTION public.get_futures_time_bau_end_num(
	contract bigint,
	end_dt timestamp with time zone,
	num_bars INT,
	adj_finish_dt timestamp with time zone,
	use_futures_no integer DEFAULT 0
)
RETURNS TABLE(
	stream_id BIGINT,
	open_dt timestamp with time zone,
	close_dt timestamp with time zone,
	open double precision,
	high double precision,
	low double precision,
	close double precision,
	face_volume double precision,
	dollar_value double precision,
	contract_id bigint,
	period bigint
)
LANGUAGE 'sql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
	
WITH contracts AS (
	SELECT
		c.contract_id,
		c.first_trading_dt,
		c.rollover_dt,
		c.primary_datafeed_id,
		ROW_NUMBER() OVER () as period
	FROM
		public.contracts c
	WHERE
		c.parent_contract_id = contract
		AND c.rollover_dt >= end_dt
	ORDER BY
		rollover_dt
), start_date AS (
	SELECT
		MIN(open_dt) as start_dt
	FROM
	(
		SELECT
			b.open_dt
		FROM
			public.time_bau b
			INNER JOIN public.streams s ON s.stream_id = b.stream_id
			INNER JOIN contracts c ON s.contract_id = c.contract_id AND s.datafeed_id = c.primary_datafeed_id AND c.period = use_futures_no + 1
		WHERE
			b.open_dt < end_dt
		ORDER BY
			b.open_dt DESC
		LIMIT
			num_bars
	) sel
), prices AS
(
	SELECT
		*
	FROM
		(
			SELECT
				GREATEST(MIN(sel.dt), (SELECT start_dt from start_date LIMIT 1)) AS start,
				MAX(sel.dt) AS end,
				sel.contract_id,
				sel.period - use_futures_no AS period
			FROM
				(
					SELECT 
						series.dt,
						c.contract_id,
						c.period,
						ROW_NUMBER() OVER (PARTITION BY series.dt ORDER BY c.rollover_dt ASC) as contract_no
					FROM 
						(
							SELECT generate_series as dt FROM generate_series((SELECT start_dt from start_date LIMIT 1), end_dt, INTERVAL '1 minute')
						) series
						LEFT JOIN contracts c ON c.rollover_dt >= series.dt AND c.first_trading_dt <= series.dt
				) sel
			WHERE
				sel.contract_no = use_futures_no + 1
			GROUP BY
				sel.contract_id, sel.period
		) periods
		INNER JOIN LATERAL 
			public.get_contract_time_bau_start_end(periods.contract_id, GREATEST(periods.start, (SELECT start_dt from start_date LIMIT 1)), periods.end) ON true
), rollovers AS
(
	SELECT
		sel.period,
		sel.delta,
		SUM(sel.delta) OVER (ORDER BY sel.period DESC) as total_delta
	FROM
	(
		SELECT
			p.period,
			n.close - p.close as delta
		FROM
			prices p
			LEFT JOIN prices n on n.start = p.end
		WHERE
			p.close_dt = p.end
			AND n.open_dt < n.start
	) sel
), raw AS
(
	SELECT
		main.stream_id,
		main.open_dt as dt,
		main.close_dt,
		main.open + COALESCE(r.total_delta, 0) AS open,
		main.high + COALESCE(r.total_delta, 0) AS high,
		main.low + COALESCE(r.total_delta, 0) AS low,
		main.close + COALESCE(r.total_delta, 0) AS close,
		main.face_volume,
		main.dollar_value,
		main.contract_id,
		main.period
	FROM
		prices main
		LEFT JOIN rollovers r ON r.period = main.period
	WHERE
		main.open_dt >= main.start
		AND main.open_dt < end_dt
)
SELECT
    stream_id,
    dt as open_dt,
    close_dt,
    open,
    high,
    low,
    close,
    face_volume,
    dollar_value,
    contract_id,
    period
FROM
    raw
ORDER BY
    open_dt;
$BODY$;


CREATE OR REPLACE FUNCTION public.get_contract_time_bau_start_end_universal(
	contract bigint,
	start_dt timestamp with time zone,
	end_dt timestamp with time zone,
	use_futures_no int
)
RETURNS TABLE (
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision, 
	total_dividends double precision, 
	factor double precision,
	contract_id bigint,
	period bigint
)
LANGUAGE 'plpgsql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
contract_type TEXT;
	parent_contract_id BIGINT;
BEGIN
SELECT
    c.type
INTO
    contract_type
FROM
    public.contracts c
WHERE
        c.contract_id = contract
    LIMIT 1;

SELECT
    c.parent_contract_id
INTO
    parent_contract_id
FROM
    public.contracts c
WHERE
        c.contract_id = contract
    LIMIT 1;

IF (contract_type = 'Futures' AND parent_contract_id IS NULL) THEN
		RETURN QUERY
SELECT
    f.stream_id,
    f.open_dt,
    f.close_dt,
    f.open,
    f.high,
    f.low,
    f.close,
    f.face_volume,
    f.dollar_value,
    CAST (0.0 AS DOUBLE PRECISION) AS total_dividends,
    CAST (1.0 AS DOUBLE PRECISION) AS factor,
    f.contract_id,
    f.period
FROM
    public.get_futures_time_bau_start_end(contract, start_dt, end_dt, use_futures_no) f;
END IF;

RETURN QUERY
SELECT
    f.stream_id,
    f.open_dt,
    f.close_dt,
    f.open,
    f.high,
    f.low,
    f.close,
    f.face_volume,
    f.dollar_value,
    f.total_dividends,
    f.factor,
    contract AS contract_id,
    CAST (0 AS BIGINT) AS period
FROM
    public.get_contract_time_bau_start_end(contract, start_dt, end_dt) f;
END;
$BODY$;

CREATE OR REPLACE FUNCTION public.get_contract_time_bau_end_num_universal(
	contract bigint,
	end_dt timestamp with time zone,
	num_bars INT,
	adj_finish_dt timestamp with time zone,
	use_futures_no int
)
RETURNS TABLE (
	stream_id BIGINT,
	open_dt timestamp with time zone, 
	close_dt timestamp with time zone, 
	open double precision, 
	high double precision, 
	low double precision, 
	close double precision, 
	face_volume double precision, 
	dollar_value double precision, 
	total_dividends double precision, 
	factor double precision,
	contract_id bigint,
	period bigint
)
LANGUAGE 'plpgsql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
contract_type TEXT;
	parent_contract_id BIGINT;
BEGIN
SELECT
    c.type
INTO
    contract_type
FROM
    public.contracts c
WHERE
        c.contract_id = contract
    LIMIT 1;

SELECT
    c.parent_contract_id
INTO
    parent_contract_id
FROM
    public.contracts c
WHERE
        c.contract_id = contract
    LIMIT 1;

IF (contract_type = 'Futures' AND parent_contract_id IS NULL) THEN
		RETURN QUERY
SELECT
    f.stream_id,
    f.open_dt,
    f.close_dt,
    f.open,
    f.high,
    f.low,
    f.close,
    f.face_volume,
    f.dollar_value,
    CAST (0.0 AS DOUBLE PRECISION) AS total_dividends,
    CAST (1.0 AS DOUBLE PRECISION) AS factor,
    f.contract_id,
    f.period
FROM
    public.get_futures_time_bau_end_num(contract, end_dt, num_bars, adj_finish_dt, use_futures_no) f;
END IF;

RETURN QUERY
SELECT
    f.stream_id,
    f.open_dt,
    f.close_dt,
    f.open,
    f.high,
    f.low,
    f.close,
    f.face_volume,
    f.dollar_value,
    f.total_dividends,
    f.factor,
    contract AS contract_id,
    CAST (0 AS BIGINT) AS period
FROM
    public.get_contract_time_bau_end_num(contract, end_dt, num_bars, adj_finish_dt) f;
END;
$BODY$;

-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
-- VALUES ('20231023084754_Initial', '9.0.6');
-- 
-- COMMIT;