namespace QuantInfra.Connectors.Binance.Common;

public interface IBinanceActiveSubscriptionsRepository :
    QuantInfra.Sdk.MarketData.IActiveSubscriptionsRepository<BinanceUsdmMarketDataSubscriptionRequest, BinanceUsdmMarketDataSubscription, BinanceUsdmMarketDataSubscriptionListView>
{
}