namespace QuantInfra.Connectors.Binance.Common;

public interface IBinanceOrderBookSubscriptionsRepository :
    Sdk.MarketData.IActiveSubscriptionsRepository<BinanceUsdmOrderBookSubscriptionRequest, BinanceUsdmOrderBookSubscription, BinanceUsdmOrderBookSubscriptionListView>
{
}