// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantInfra.Databases.Backtesting.Sqlite;

#nullable disable

namespace QuantInfra.Databases.Backtesting.Sqlite.Migrations
{
    [DbContext(typeof(BacktestingContext))]
    partial class BacktestingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("QuantInfra.Common.Interfaces.Api.Backtesting.TestUnitStatusRecord", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ContractOverride")
                        .HasColumnType("string")
                        .HasColumnName("contract_override");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("MetricsCalculatorName")
                        .HasColumnType("TEXT")
                        .HasColumnName("metrics_calculator_name");

                    b.Property<string>("MetricsCalculorData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metrics_calculator_data");

                    b.Property<int>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_message");

                    b.HasKey("TestId");

                    b.ToTable("test_units", (string)null);
                });

            modelBuilder.Entity("QuantInfra.Common.Interfaces.Api.Backtesting.TestUnitStatusRecord", b =>
                {
                    b.OwnsOne("QuantInfra.Sdk.Backtesting.PersistOptions", "PersistOptions", b1 =>
                        {
                            b1.Property<Guid>("TestUnitStatusRecordTestId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("DoNotSaveZeroDailyReturns")
                                .HasColumnType("INTEGER")
                                .HasColumnName("skip_zero_daily_returns");

                            b1.Property<int>("ExpectedNumberOfOpenPositionsAtEndOfDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("expected_positions_per_day");

                            b1.Property<int>("ExpectedNumberOfTradesPerDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("expected_trades_per_day");

                            b1.Property<bool>("SaveDailyReturns")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_daily_returns");

                            b1.Property<bool>("SaveEndOfDayValues")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_end_of_day_values");

                            b1.Property<bool>("SaveMetrics")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_metrics");

                            b1.Property<bool>("SavePositions")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_positions");

                            b1.Property<bool>("SaveStrategies")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_strategies");

                            b1.Property<bool>("SaveTrades")
                                .HasColumnType("INTEGER")
                                .HasColumnName("save_trades");

                            b1.HasKey("TestUnitStatusRecordTestId");

                            b1.ToTable("test_units");

                            b1.WithOwner()
                                .HasForeignKey("TestUnitStatusRecordTestId");
                        });

                    b.OwnsOne("QuantInfra.Sdk.Backtesting.TestExecutorOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("TestUnitStatusRecordTestId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CandlesTimeframe")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("candles_timeframe");

                            b1.Property<bool>("CheckOrdersAtBarClose")
                                .HasColumnType("INTEGER")
                                .HasColumnName("check_orders_at_bar_close");

                            b1.Property<bool>("CheckOrdersAtBarOpen")
                                .HasColumnType("INTEGER")
                                .HasColumnName("check_orders_at_bar_open");

                            b1.Property<bool>("CheckPendingOrdersExecutionUsingHighLow")
                                .HasColumnType("INTEGER")
                                .HasColumnName("check_pending_orders_execution_using_high_low");

                            b1.Property<string>("EndDt")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("end_dt");

                            b1.Property<string>("HighLowExecutionOffset")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("high_low_execution_offset");

                            b1.Property<decimal>("Investment")
                                .HasColumnType("TEXT")
                                .HasColumnName("investment");

                            b1.Property<bool>("LimitCloseCheckToMarketOrdersOnly")
                                .HasColumnType("INTEGER")
                                .HasColumnName("limit_close_check_to_market_orders_only");

                            b1.Property<int>("LogLevel")
                                .HasColumnType("INTEGER")
                                .HasColumnName("log_level");

                            b1.Property<string>("MtmUtcOffset")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("mtm_utc_offset");

                            b1.Property<string>("OpenExecutionOffset")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("open_execution_offset");

                            b1.Property<int>("RequestBarAttempts")
                                .HasColumnType("INTEGER")
                                .HasColumnName("request_bar_attempts");

                            b1.Property<string>("StartDt")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("start_dt");

                            b1.Property<int>("StopOrdersExecution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("stop_orders_execution");

                            b1.Property<bool>("ThrowOnZeroVolumeOrders")
                                .HasColumnType("INTEGER")
                                .HasColumnName("throw_on_zero_volume_orders");

                            b1.Property<int>("VirtualAccountSizeStepFraction")
                                .HasColumnType("INTEGER")
                                .HasColumnName("virtual_account_size_step_fraction");

                            b1.HasKey("TestUnitStatusRecordTestId");

                            b1.ToTable("test_units");

                            b1.WithOwner()
                                .HasForeignKey("TestUnitStatusRecordTestId");
                        });

                    b.Navigation("Options")
                        .IsRequired();

                    b.Navigation("PersistOptions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
