// <auto-generated />
using System;
using Databases.MarketDataHistory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Databases.MarketDataHistory.Migrations
{
    [DbContext(typeof(MDTimescaleContextDesign))]
    [Migration("20240222094333_SynthFuturesBugFix")]
    partial class SynthFuturesBugFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Databases.MarketDataHistory.Models.CorporateEvents.Dividend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dividend_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<Instant>("ExDividendDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ex_dividend_date");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ExDividendDate");

                    b.HasIndex("Id");

                    b.ToTable("dividends");
                });

            modelBuilder.Entity("Databases.MarketDataHistory.Models.CorporateEvents.RollingContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<Instant>("EndDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_dt");

                    b.Property<long>("ParentContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_contract_id");

                    b.Property<Instant>("StartDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_dt");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EndDt");

                    b.HasIndex("ParentContractId");

                    b.HasIndex("StartDt");

                    b.ToTable("rolling_contracts");
                });

            modelBuilder.Entity("Databases.MarketDataHistory.Models.CorporateEvents.Split", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("split_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<Instant>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt");

                    b.Property<double>("Factor")
                        .HasColumnType("double precision")
                        .HasColumnName("factor");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Dt");

                    b.ToTable("splits");
                });

            modelBuilder.Entity("Databases.MarketDataHistory.Models.DollarValueBAU", b =>
                {
                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<Instant>("CloseDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_dt");

                    b.Property<double>("DollarValue")
                        .HasColumnType("double precision")
                        .HasColumnName("dollar_value");

                    b.Property<double>("FaceVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("face_volume");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<Instant>("OpenDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_dt");

                    b.Property<long>("StreamId")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_id");

                    b.ToTable("dollar_value_bau");
                });

            modelBuilder.Entity("Databases.MarketDataHistory.Models.FaceVolumeBAU", b =>
                {
                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<Instant>("CloseDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_dt");

                    b.Property<double>("DollarValue")
                        .HasColumnType("double precision")
                        .HasColumnName("dollar_value");

                    b.Property<double>("FaceVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("face_volume");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<Instant>("OpenDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_dt");

                    b.Property<long>("StreamId")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_id");

                    b.ToTable("face_volume_bau");
                });

            modelBuilder.Entity("Databases.MarketDataHistory.Models.TimeBAU", b =>
                {
                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<Instant>("CloseDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_dt");

                    b.Property<double>("DollarValue")
                        .HasColumnType("double precision")
                        .HasColumnName("dollar_value");

                    b.Property<double>("FaceVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("face_volume");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<Instant>("OpenDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_dt");

                    b.Property<long>("StreamId")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_id");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("trading_session_id");

                    b.ToTable("time_bau");
                });
#pragma warning restore 612, 618
        }
    }
}
