// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantInfra.Databases.MarketDataHistory;

#nullable disable

namespace QuantInfra.Databases.MarketDataHistory.Migrations
{
    [DbContext(typeof(MDTimescaleContextDesign))]
    [Migration("20260717153944_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantInfra.Databases.MarketDataHistory.Models.TimeBAU", b =>
                {
                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<Instant>("CloseDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_dt");

                    b.Property<double>("DollarValue")
                        .HasColumnType("double precision")
                        .HasColumnName("dollar_value");

                    b.Property<double>("FaceVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("face_volume");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<Instant>("OpenDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_dt");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer")
                        .HasColumnName("stream_id");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("trading_session_id");

                    b.ToTable("time_bau");
                });
#pragma warning restore 612, 618
        }
    }
}
